packages:
  - .

overrides:
  effect: ^4.0.0-rc.116
  '@effect/platform-browser': ^4.0.0-rc.116
  '@effect/platform-node': ^4.0.0-rc.116
  '@effect/platform-node-shared': ^4.0.0-rc.116
  react: ^19.3.0
  react-dom: ^19.3.0
  vite: npm:@voidzero-dev/vite-plus-core@^0.3.1

allowBuilds:
  workerd: true
  esbuild: true
  msgpackr-extract: false
